# Generated by Django 2.2 on 2020-06-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='test_app.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.IntegerField(default=-1),
        ),
    ]
