# Generated by Django 2.2 on 2020-07-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200622_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='painting',
        ),
    ]
