# Generated by Django 2.2 on 2020-07-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_post_painting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
