# Generated by Django 2.2 on 2020-08-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_auto_20200823_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
