# Generated by Django 2.2 on 2021-02-25 17:43

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_auto_20210225_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='painting',
            field=models.TextField(default='/Hearthstone_Screenshot_06-12-20_23.02.24.png'),
        ),
    ]
